---

sqlConnection :
 user : ""
 password : ""
 host : ""
 db : ""


serviceExecuteData :
 apiKey : ""
 apiURL : "http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson"
 hostermail : ""
 hostermailpw : ""
 bitlykey : ""
...
